name: eco_track
description: Eco-Track Flutter App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.3.0
  flutter_image_compress: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/eco_bg.png
    - assets/eco_logo.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/eco_logo.png"
